### PR TITLE
Implement serialization of G4HepEmData data to JSON

### PR DESCRIPTION
**Pull request by drbenmorgan**
This provides the basic JSON (de)serialization for `G4HepEmData` objects as discussed in #36. 

It imports [`nlohmann_json`](https://github.com/nlohmann/json) to do the heavy lifting, and it's imported rather than used as an external (`find_package`) purely for simplicity at this point. The use of this library is hidden in `G4HepEmData`, with only the `G4HepEmData{To,From}Json` functions available to clients. Only `G4HepEmData` is (de)serialized directly, all other data structures being recursively serialised behind the scenes.

The `DataImportExport` test has been updated to exercise things by:

- Constructing either a "simple" (three materials, two regions) or "full" (`FakeG4Setup` as used by other tests) setup
- Serializing the created `G4HepEmData` object to a JSON file
- Constructing a new `G4HepEmData` object from the JSON file created at the previous step
- Confirming via deep comparison that all values in both objects are equal.
 
Note that this last step requires #39 otherwise the round trip test will fail due to initialization differences. So I expect this to fail, but I will rebase once #39 is merged.

The file output by the "full" setup is quite large at around 25MB, but I don't think this is terrible for the current purpose here (and read/construction still seems quicker than from scratch calculation!).

Fixes: #36

### CODE REVIEW

**Comment by drbenmorgan** [comment]
Tests failed, but exactly as expected - so will wait for #39 and then rebase.

**Comment by mnovak42** [comment]
#39 is merged now to the master.

**Comment by mnovak42** [comment]
We might need to consider to relocate all read/write (and related) functionalities that are not necessary at simulation run-time out of the `G4HepEmData` library (e.g. to the `G4HepEmInit` that depends on `G4HepEmData`). This is because it was supposed to
 - contain only definitions of the data structures without any dependencies
 - be as small as possible since this is used heavily at run time

**Comment by drbenmorgan** [comment]
Thanks! Rebased on `master` and updated.

On the location of the I/O part - maybe a separate `G4HepEmDataIO` (or even `G4HepEmDataJsonIO`) library? It makes sense to keep it separate, though I think it has to be alongside rather than in Init/Run because we want to decouple things from Geant4 dependence.

I can make the separate library pretty quickly (it's just a build change) if you'd rather it go in right now.

**Comment by mnovak42** [comment]
Yes, you are right, it's better to have it as a separate `G4HepEmDataIO` in order to decouple it from `Geant4`. Please, juts go ahead and make it if you can do it easily. 

Just let me know if you prefer this PR to be merged first and do it in a new one or you would like to make it already in this PR.

**Comment by drbenmorgan** [comment]
O.k., will do the change now!

**Comment by drbenmorgan** [comment]
Done - there's now a separate `g4HepEmDataJsonIO` library. Nothing more than the code added in the initial commit factored out into a separate library.

That's actually a _much_ better pattern as it could be used in the future to provide additional serialization options if externals are available (e.g. HDF5, ROOT) without changing `g4HepEMData` itself.

**Pull request merged**
