### PR TITLE
Simplify build and use of unit/example tests for CPU/CUDA

### PR DESCRIPTION
**Pull request by drbenmorgan**
This is a straightforward, but large, PR to simplify how tests are build and used in G4HepEm. Whilst the tests are also examples of use, especially for CUDA, they are not and should not be individual projects. This both encourages clients to error prone cut-and-paste and makes the build/test inside G4HepEM over-complex.

To address both points, the unit test codes are moved from `apps/tests` to `testing` directly and added to the build via `add_subdirectory`. Each test's build is simplified down to the minimal needed `add_executable`, usage requirement commands, and `add_test` calls. Instead of compiling the `TestUtils` code once for every test, it is complied as a separate static library and linked to the final test executables, reducing the amount of compilation whilst reproducing behaviour. This also makes adding new tests much easier with a direct and simple template.

The TestEm3 example is left in place as a true example, its integration in the tests now using a simple `add_subdirectory` to ensure the build is tested uniformly with the rest of the G4HepEm build.

### CODE REVIEW

**Comment by mnovak42** [comment]
`testElectronInteractionBrem`  is an application for the developer to perform some tests regarding the
   
  1. correctness of final state generation of the bremsstrahlung interaction models by comparing the histograms provided by using `G4HepEm` to the corresponding outputs generated by using native `Geant4` models 
  2. it can also be used to test the host-device side consistency of the `G4HepEm` Seltzer-Berger bremsstrahlung sampling tables used to generate fractional energy transferred to the emitted photon when the interaction is modelled by the Seltzer-Berger differential cross sections      
  
While both 1. and 2. could be executed as unit tests
 1.  doesn't make much sense since the resulted histograms are not checked. But it would be very important for the developer to be able to build this test as a standalone application anytime (with its own CMakeFile as before) when occasional teasing is required. 
 2.  this requires CUDA enable build and the execution requires a device (this can be done only in case of local testing since GitHub CI do not provide any device)  
 
In any case, we need to make sure that we provide the appropriate input arguments to this application to perform the required testing. Here are the output of the application regarding its input arguments with their default values: 

    ======================================================================================
      Model-level test for testing e-/e+ bremsstrahlung photon emission intercation models.

      Usage: testBrem [OPTIONS] 
    

	  -t  --test-type         (G4HepEm`, `G4` or `GPU(data)`)    - default: HepEm
	  -p  --particle-name     (`e-` or `e+`)                     - default: e-
	  -m  --material-name     (G4-NIST mat. name,`G4_` prefix)   - default: G4_Pb
	  -e  --primary-energy    (kinetic energy in [MeV])          - default: 234.56
	  -f  --number-of-samples (number of required samples)       - default: 1.e+7
	  -n  --number-of-bins    (number of bins in the histograms) - default: 100
	  -b  --model-name        (`bremS` or `bremRel`)             - default: bremSB
	  -c  --cut-vale          (secondary prod. thresh. in [mm])  - default: 0.7
	  -h  --help

     ======================================================================================

**Comment by drbenmorgan** [comment]
Thanks for the info on `testElectronInteractionBrem`, but just to clarify one thing on:

> While both 1. and 2. could be executed as unit tests
> 
> 1. doesn't make much sense since the resulted histograms are not checked. But it would be very important for the developer to be able to build this test as a standalone application anytime (with its own CMakeFile as before) when occasional teasing is required.

Does this mean it is closer to an example - i.e. you expect the code to be copied, built and used completely outside of a G4HepEM source/build tree as a totally independent program/project? 

The build of it in this PR still results in a program the developer can run manually for the testing use cases outlined - its location in `testing` just reflects that it is a test more than it being/requiring automation (and it sounds like that's not required/intended now, which is fine).

**Comment by mnovak42** [comment]
Well, these type of `tests` are those that usually we do not expose to the users. In `Geant4`, these type of tests are usually in our (not public) `verification` repository since they are intended to be used only by the model developer. So actually they should not be used or seen at all by any users :) . However, since `G4HepEm` as a whole is an `R&D`, i.e. a public repository of some developers, (shared in order to let everyone benefit form it who can), it naturally contains everything. 

It's fine to me to put this among the other unit tests, but it's good to keep in mind that these are actually different: while the others will fail if something is wrong since they test pure technical correctness (i.e. data consistency, basic interpolation functions, etc.)  this type of tests will pass even if the underlying functionality is producing complete nonsense. I might revisit this later and add some reference distributions to the default execution in order to have something against to check.

So it's fine to me.

However, I would have 2 additional small points regarding the changes in this PR:
1. when `include(CTest)` is used it adds the `BUILD_TESTING` `CMake` variable with the default **ON** value. So with this PR we would have `testing` **active by default** (if I'm right). Can we modify this just to have **by default the testing OFF**. (e.g. by defining the `BUILD_TESTING` option just above  the `include(CTest)` with the default **OFF** value if it makes it.)
2. I have provided a `Readme` file for each unit tests that also includes example on how to build and execute them. These (among other information in these `Readme` files) became obsolete. So could you please update or hist simple delete them in order to avoid any confusions later?

**Comment by drbenmorgan** [comment]
O.k., `Readme`s simplified to just include details on what the test does, and `BUILD_TESTING` defaulted to `OFF`. This shouldn't affect CI since the workflow scripts explicitly set it to `ON`.

**Pull request merged**
